version: 2

models:
  - name: int_accounts
    description: "Intermediate account model built from Salesforce account staging data."
    columns:
      - name: account_id
        description: "Unique Salesforce account identifier."
        tests:
          - not_null
          - unique
      - name: created_date
        description: "Account creation timestamp cast to timestamp."
        tests:
          - not_null
      - name: last_modified_date
        description: "Last modified timestamp cast to timestamp."
      - name: is_deleted
        description: "Indicates if account is deleted"
        tests:
          - accepted_values:
              arguments:
                values: [0]
      - name: system_modstamp
        description: "System modification timestamp cast to timestamp."
